# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlanCreatorDialog
                                 A QGIS plugin
 Инструмент создания пространственно-информационной модели здания
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-27
        git sha              : $Format:%H$
        copyright            : (C) 2021 by bvchirkov
        email                : b.v.chirkov@udsu.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CREATE_PROJ, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'plan_creator_dialog_base.ui'))

FORM_CREATE_LEVEL, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'plan_creator_dialog_level.ui'))

class PlanCreatorDialogCreateProj(QtWidgets.QDialog, FORM_CREATE_PROJ):
    def __init__(self, parent=None):
        """Constructor."""
        super(PlanCreatorDialogCreateProj, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CREATE_PROJ.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class PlanCreatorDialogCreateLevel(QtWidgets.QDialog, FORM_CREATE_LEVEL):
    def __init__(self, parent=None):
        """Constructor."""
        super(PlanCreatorDialogCreateLevel, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CREATE_LEVEL.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)        